---
workspace: /root
sonar_download_validate_certs: yes

# Default to the latest LTS release.
sonar_version: 4.5.6
sonar_download_url: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-{{ sonar_version }}.zip"
sonar_version_directory: "sonarqube-{{ sonar_version }}"

sonar_web_context: ''

# MySQL database connection details.
sonar_mysql_username: sonar
sonar_mysql_password: sonar

sonar_mysql_host: localhost
sonar_mysql_port: "3306"
sonar_mysql_database: sonar

sonar_mysql_allowed_hosts:
  - "127.0.0.1"
  - "::1"
  - "localhost"

sonar_owner                              : "sonar"
sonar_group                              : "sonar"
sonar_shell                              : "/bin/bash"
sonar_base_dir                           : "/usr/local/sonar"


sonar_admin_password                     : "admin"
sonar_jenkins_token                      : "123456"