Vagrant.configure("2") do |config|
  config.vm.box = ENV['BOX_NAME']
  config.vm.box_check_update = false
  config.vm.provider :lxc do |lxc|
    # Same effect as 'customize ["modifyvm", :id, "--memory", "1024"]' for VirtualBox
    # lxc.customize 'cgroup.memory.limit_in_bytes', '7524M'
    lxc.customize 'apparmor.profile', 'unconfined' # added to be able run Docker inside LXC, it is not secure? do we have alternatives?
    lxc.customize 'net.0.ipv4.address', '10.0.3.16/24' # LXC 3.0
  end
end
