jenkins_directory: /data/jenkins

directories:
  - '{{ jenkins_directory }}/plugins'
  - '{{ jenkins_directory }}/slaves/cd'
  - /data/.ivy2

jobs:
  - books-service

# Optional method of pinning a specific version of Jenkins and/or overriding the
# default Jenkins packaging URL.
jenkins_version: "2.107.3"
# jenkins_pkg_url: "https://www.example.com"

# Change this to `latest` to update Jenkins if a newer version is available.
jenkins_package_state: present

jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_home: /var/lib/jenkins
jenkins_hostname: localhost
jenkins_http_port: 8090
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_url_prefix: ""
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"

jenkins_plugins:
- name: jquery
  version: "1.12.4-0"
- name: momentjs
  version: "1.1.1"
- name: antisamy-markup-formatter
  version: "1.5"
- name: authentication-tokens
  version: "1.3"
- name: workflow-scm-step
  version: "2.7"
- name: mapdb-api
  version: "1.0.9.0"
- name: pmd
  version: "3.50"
- name: zapper
  version: "1.0.7"
- name: plain-credentials
  version: "1.4"
- name: workflow-step-api
  version: "2.16"
- name: subversion
  version: "2.12.1"
- name: pipeline-graph-analysis
  version: "1.7"
- name: scm-api
  version: "2.2.8"
- name: jquery-detached
  version: "1.2.1"
- name: custom-tools-plugin
  version: "0.5"
- name: jdk-tool
  version: "1.1"
- name: thinBackup
  version: "1.9"
- name: matrix-auth
  version: "2.3"
- name: code-coverage-api
  version: "1.0.5"
- name: groovy
  version: "2.0"
- name: pipeline-model-declarative-agent
  version: "1.1.1"
- name: pipeline-rest-api
  version: "2.10"
- name: violations
  version: "0.7.11"
- name: credentials
  version: "2.1.18"
- name: ldap
  version: "1.20"
- name: pipeline-stage-tags-metadata
  version: "1.3.2"
- name: jsch
  version: "0.1.54.2"
- name: ant
  version: "1.8"
- name: workflow-cps-global-lib
  version: "2.12"
- name: docker-workflow
  version: "1.17"
- name: pipeline-milestone-step
  version: "1.3.1"
- name: lockable-resources
  version: "2.3"
- name: conditional-buildstep
  version: "1.3.6"
- name: credentials-binding
  version: "1.16"
- name: pipeline-model-api
  version: "1.3.2"
- name: pipeline-stage-step
  version: "2.3"
- name: jackson2-api
  version: "2.8.11.3"
- name: pipeline-model-extensions
  version: "1.3.2"
- name: sonar
  version: "2.8.1"
- name: pam-auth
  version: "1.4"
- name: workflow-multibranch
  version: "2.20"
- name: gitlab-oauth
  version: "1.4"
- name: analysis-core
  version: "1.95"
- name: cvs
  version: "2.14"
- name: token-macro
  version: "2.5"
- name: docker-commons
  version: "1.13"
- name: workflow-api
  version: "2.29"
- name: git-server
  version: "1.7"
- name: postbuildscript
  version: "2.8.1"
- name: script-security
  version: "1.46"
- name: ruby-runtime
  version: "0.12"
- name: ssh-slaves
  version: "1.28.1"
- name: cobertura
  version: "1.13"
- name: mashup-portlets-plugin
  version: "1.0.9"
- name: windows-slaves
  version: "1.3.1"
- name: handlebars
  version: "1.1.1"
- name: gradle
  version: "1.29"
- name: apache-httpcomponents-client-4-api
  version: "4.5.5-3.0"
- name: mailer
  version: "1.21"
- name: pipeline-input-step
  version: "2.8"
- name: checkstyle
  version: "3.50"
- name: run-condition
  version: "1.2"
- name: build-timeout
  version: "1.19"
- name: workflow-durable-task-step
  version: "2.22"
- name: nodejs
  version: "1.2.6"
- name: git
  version: "3.9.1"
- name: gitlab-merge-request-jenkins
  version: "2.0.0"
- name: pipeline-model-definition
  version: "1.3.2"
- name: bouncycastle-api
  version: "2.17"
- name: analysis-collector
  version: "1.52"
- name: pipeline-build-step
  version: "2.7"
- name: dashboard-view
  version: "2.9.11"
- name: durable-task
  version: "1.26"
- name: git-client
  version: "2.7.3"
- name: translation
  version: "1.16"
- name: config-file-provider
  version: "3.2"
- name: workflow-job
  version: "2.25"
- name: instant-messaging
  version: "1.35"
- name: ace-editor
  version: "1.1"
- name: workflow-support
  version: "2.20"
- name: pipeline-multibranch-defaults
  version: "2.0"
- name: workflow-cps
  version: "2.57"
- name: parameterized-trigger
  version: "2.35.2"
- name: junit
  version: "1.26.1"
- name: matrix-project
  version: "1.13"
- name: command-launcher
  version: "1.2"
- name: ircbot
  version: "2.30"
- name: pipeline-stage-view
  version: "2.10"
- name: gitlab-plugin
  version: "1.5.10"
- name: external-monitor-job
  version: "1.7"
- name: workflow-aggregator
  version: "2.6"
- name: display-url-api
  version: "2.2.0"
- name: cloudbees-folder
  version: "6.6"
- name: structs
  version: "1.17"
- name: maven-plugin
  version: "3.1.2"
- name: branch-api
  version: "2.0.20"
- name: postbuild-task
  version: "1.8"
- name: extended-choice-parameter
  version: "0.76"
- name: xvfb
  version: "1.1.3"
- name: gitlab-hook
  version: "1.4.2"
- name: ssh-credentials
  version: "1.14"
- name: zaproxy
  version: "1.1.5"
- name: workflow-basic-steps
  version: "2.11"
- name: javadoc
  version: "1.4"
- name: findbugs
  version: "4.72"


jenkins_plugins_state: present
jenkins_plugin_updates_expiration: 86400
jenkins_plugin_timeout: 30

jenkins_admin_username: jenkins-admin
jenkins_admin_password: NA2x8k27CNU7wg39W
jenkins_admin_password_file: ""
jenkins_admin_token: ""
jenkins_admin_token_file: ""

jenkins_process_user: jenkins
jenkins_process_group: "{{ jenkins_process_user }}"

jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }}"
  - option: "{{ jenkins_java_options_env_var }}"
    value: "{{ jenkins_java_options }}"

#jenkins_admin_token: "{{ lookup('file', '/var/lib/jenkins/secrets/initialAdminPassword') }}"

jenkins_ssh_key_file: "/home/ev/.ssh/id_rsa_jenkins_github"

jenkins_ssh_fingerprints:                   # Set known hosts for ssh
  - "bitbucket.org,131.103.20.167 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw=="
  - "github.com,204.232.175.90 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
