---
# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Check if MySQL packages were installed.
  set_fact:
    mysql_install_packages: "{{ (rh_mysql_install_packages is defined and rh_mysql_install_packages.changed)
      or (deb_mysql_install_packages is defined and deb_mysql_install_packages.changed)
      or (arch_mysql_install_packages is defined and arch_mysql_install_packages.changed) }}"

# Configure MySQL.
- include_tasks: configure.yml
- include_tasks: secure-installation.yml
- include_tasks: databases.yml
- include_tasks: users.yml
- include_tasks: replication.yml


- name: Copy irc_log_bot_schema.sql
  copy:
    src: irc_log_bot_schema.sql
    dest: /tmp/irc_log_bot_schema.sql

- name: import irc_log_bot_schema
#  command: "mysql -u root -proot irc_log_bot < /tmp/irc_log_bot_schema.sql"
  mysql_db: name=irc_log_bot state=import target=/tmp/irc_log_bot_schema.sql