---
- name: Ensure that the nginx package is installed
  tags: nginx
  become: true
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Attempting to overlay nginx configuration
  copy:
    src: gitlab-omnibus-nginx.conf
    dest: /etc/nginx/sites-enabled/gitlab-omnibus-nginx.conf
#    mode: 0600
#    owner: irc
#    group: irc
#  with_items:
#    - nginx_default

- name: Remove nginx default page.
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Ensure that nginx is started and enabled on boot
  tags: nginx
  become: true
  service:
    enabled: yes
    name: nginx
#    state: started
    state: restarted

...
