---
- hosts:
  - all
  - localhost
  become: true
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python
    - name: Gathering facts
      setup:
  vars:
    - vagrant_version: "2.1.4"
    - vagrant_lxc_enabled: true

  roles:
    - ansible-vagrant-role
