---
- name: Remove all Sonar plugins to install only required
  shell: rm -rf {{ __sonar_plugin_home }}/*

- name: "Install SonarQube plugins"
  get_url:
    url: "{% if item.url is defined and item.url != '' %}{{ item.url }}{% else %}{% if item.commercial %}{{ __sonar_commercial_plugin_baseurl }}{% else %}{{ __sonar_plugin_baseurl }}{% endif %}/{{ item.name }}/{{ item.name }}-{{ item.version }}.jar{% endif %}"
    dest: "{{ __sonar_plugin_home }}/{{ item.name }}-{{ item.version }}.jar"
    owner: "{{ sonar_owner }}"
    group: "{{ sonar_group }}"
  with_items: "{{ sonar_plugins }}"
  retries: 5
  delay: 10
  notify: restart sonar

